name: CI
on: [push, pull_request]

env:
  libarchive_tag: v3.7.2

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'ubuntu-22.04']
        version: ['3.9', '3.10']
        exclude:
          - os: 'ubuntu-20.04'
            version: '3.10'
          - os: 'ubuntu-22.04'
            version: '3.9'
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install host dependencies
      run: sudo apt update && sudo apt install -y libarchive-dev

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.version }}

    - name: Check out code
      uses: actions/checkout@v4

    - name: Build the library
      env:
        PYVER: ${{ matrix.version }}
      run: make build

    - name: Run tests
      run: make test
      
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        CIBW_ENVIRONMENT: INCLUDE=/usr/local/include  LIBARCHIVE_PREFIX=/usr/local
        CIBW_PROJECT_REQUIRES_PYTHON: ">=3.9"
        CIBW_ARCHS: auto64
        CIBW_SKIP: "pp* *-musllinux_*"
        CIBW_BEFORE_ALL: bash -x build-libarchive-lib.sh ubuntu ${{ env.libarchive_tag }}

    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
        retention-days: 1
